"""
🔀 Explicit order-lifecycle state machine (Phase 3).

One typed state per order, with legal transitions. An illegal transition is REJECTED and
raises `IllegalTransition` (the EMS turns that into an incident) — order state is never
silently rewritten from a soup of booleans. Every applied transition is appended to the
order's history (auditable).
"""
from __future__ import annotations

INTENT_RECEIVED = "INTENT_RECEIVED"
RISK_PENDING = "RISK_PENDING"
RISK_REJECTED = "RISK_REJECTED"
RISK_APPROVED = "RISK_APPROVED"
PLAN_CREATED = "PLAN_CREATED"
SUBMISSION_PENDING = "SUBMISSION_PENDING"
SUBMITTING = "SUBMITTING"
SUBMITTED = "SUBMITTED"
ACKNOWLEDGED = "ACKNOWLEDGED"
OPEN = "OPEN"
PARTIALLY_FILLED = "PARTIALLY_FILLED"
FILLED = "FILLED"
PROTECTION_PENDING = "PROTECTION_PENDING"
PROTECTED = "PROTECTED"
MODIFICATION_PENDING = "MODIFICATION_PENDING"
CANCELLATION_PENDING = "CANCELLATION_PENDING"
CANCELLED = "CANCELLED"
EXIT_PENDING = "EXIT_PENDING"
CLOSED = "CLOSED"
REJECTED = "REJECTED"
EXPIRED = "EXPIRED"
BROKER_UNKNOWN = "BROKER_UNKNOWN"
RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
FAILED_SAFE = "FAILED_SAFE"

_TERMINAL = {CANCELLED, CLOSED, REJECTED, EXPIRED, FAILED_SAFE, RISK_REJECTED}

_LEGAL = {
    INTENT_RECEIVED: {RISK_PENDING, FAILED_SAFE},
    RISK_PENDING: {RISK_APPROVED, RISK_REJECTED, FAILED_SAFE},
    RISK_REJECTED: set(),
    RISK_APPROVED: {PLAN_CREATED, FAILED_SAFE},
    PLAN_CREATED: {SUBMISSION_PENDING, FAILED_SAFE},
    SUBMISSION_PENDING: {SUBMITTING, FAILED_SAFE, RECONCILIATION_REQUIRED},
    SUBMITTING: {SUBMITTED, REJECTED, BROKER_UNKNOWN, RECONCILIATION_REQUIRED, FAILED_SAFE},
    SUBMITTED: {ACKNOWLEDGED, OPEN, REJECTED, PARTIALLY_FILLED, FILLED, BROKER_UNKNOWN,
                RECONCILIATION_REQUIRED},
    ACKNOWLEDGED: {OPEN, PARTIALLY_FILLED, FILLED, CANCELLATION_PENDING, REJECTED,
                   BROKER_UNKNOWN, RECONCILIATION_REQUIRED},
    OPEN: {PARTIALLY_FILLED, FILLED, CANCELLATION_PENDING, EXPIRED, MODIFICATION_PENDING,
           BROKER_UNKNOWN, RECONCILIATION_REQUIRED},
    PARTIALLY_FILLED: {PARTIALLY_FILLED, FILLED, CANCELLATION_PENDING, PROTECTION_PENDING,
                       EXPIRED, BROKER_UNKNOWN, RECONCILIATION_REQUIRED},
    FILLED: {PROTECTION_PENDING, EXIT_PENDING, RECONCILIATION_REQUIRED},
    PROTECTION_PENDING: {PROTECTED, EXIT_PENDING, FAILED_SAFE, RECONCILIATION_REQUIRED},
    PROTECTED: {EXIT_PENDING, MODIFICATION_PENDING, RECONCILIATION_REQUIRED, CLOSED},
    MODIFICATION_PENDING: {OPEN, PROTECTED, REJECTED, RECONCILIATION_REQUIRED},
    CANCELLATION_PENDING: {CANCELLED, PARTIALLY_FILLED, FILLED, RECONCILIATION_REQUIRED},
    EXIT_PENDING: {CLOSED, PARTIALLY_FILLED, RECONCILIATION_REQUIRED, FAILED_SAFE},
    BROKER_UNKNOWN: {RECONCILIATION_REQUIRED, FAILED_SAFE},
    RECONCILIATION_REQUIRED: {SUBMITTED, ACKNOWLEDGED, OPEN, PARTIALLY_FILLED, FILLED,
                              PROTECTED, CANCELLED, REJECTED, CLOSED, FAILED_SAFE},
}


class IllegalTransition(Exception):
    pass


def is_terminal(state: str) -> bool:
    return state in _TERMINAL


def can_transition(src: str, dst: str) -> bool:
    return dst in _LEGAL.get(src, set())


def apply_transition(order, dst: str, note: str = "") -> None:
    """Mutate `order.state` to `dst` if legal, appending to history. Else raise."""
    import time
    if not can_transition(order.state, dst):
        raise IllegalTransition(f"{order.state} -> {dst} is not a legal order transition")
    order.history.append((order.state, dst, round(time.time(), 3), note))
    order.state = dst
