"""Central framework registry — one dict, many business types."""

from __future__ import annotations

from product.due_diligence.frameworks_types import SectorFramework

from . import kpis as k

def _fw(
    *,
    id: str,
    label: str,
    kpis,
    min_critical: int,
    min_decision: float,
    min_score: float,
    watch: tuple[str, ...] = (),
    acquire: tuple[str, ...] = ("financials", "ir", "filings", "news"),
    material: tuple[str, ...] = (),
    skip_cfo: bool = False,
    cycle_aware: bool = False,
    lending: bool = False,
    peer_note: str = "",
    sub_sector: str = "",
    business_model: str = "",
    blurb: str = "",
) -> SectorFramework:
    crit_watch = tuple(
        f"Next {spec.label} print versus this period."
        for spec in kpis
        if spec.importance == "critical"
    )[:3]
    extra_watch = tuple(item for item in watch if " " in str(item))
    if not extra_watch and watch:
        extra_watch = (f"Watch {' / '.join(watch[:4])} if a filing actually reports them.",)
    return SectorFramework(
        id=id,
        label=label,
        kpis=kpis,
        blurb=blurb or (
            f"{label}: define what must be known for this business, then score only measured evidence."
        ),
        min_critical=min_critical,
        min_decision_coverage=min_decision,
        min_score_coverage=min_score,
        watch=crit_watch + extra_watch,
        acquire_priority=acquire,
        material_tokens=material,
        skip_cfo_conversion=skip_cfo,
        cycle_aware=cycle_aware,
        lending=lending,
        peer_note=peer_note,
        default_sub_sector=sub_sector,
        default_business_model=business_model,
    )


_IR_DEAL = ("ir", "financials", "filings", "news")
_IR_REG = ("financials", "ir", "filings", "news")
_BANK_ACQ = ("financials", "ir", "filings", "news")

FRAMEWORKS: dict[str, SectorFramework] = {
    "bank": _fw(
        id="bank",
        label="Bank",
        kpis=k.BANK,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("gnpa", "nnpa", "nim", "casa", "roa", "cet1"),
        acquire=_BANK_ACQ,
        material=("rbi", "pca", "prompt corrective", "moratorium", "capital raising", "npa"),
        skip_cfo=True,
        lending=True,
        peer_note="Compare with banks of similar franchise (private vs PSU), not NBFCs.",
        sub_sector="Banking",
        business_model="Bank",
    ),
    "nbfc": _fw(
        id="nbfc",
        label="NBFC",
        kpis=k.NBFC,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("gnpa", "nnpa", "nim", "aum", "roa"),
        acquire=_BANK_ACQ,
        material=("rbi", "nbfc", "capital raising", "liquidity", "npa"),
        skip_cfo=True,
        lending=True,
        peer_note="Compare with NBFCs of similar book (vehicle, gold, HFC, diversified), not banks.",
        sub_sector="NBFC",
        business_model="Diversified NBFC",
    ),
    "nbfc_gold": _fw(
        id="nbfc_gold",
        label="Gold-loan NBFC",
        kpis=k.NBFC_GOLD,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("gnpa", "aum", "ltv", "nim"),
        acquire=_BANK_ACQ,
        material=("rbi", "gold", "auction", "ltv"),
        skip_cfo=True,
        lending=True,
        peer_note="Gold-loan NBFCs only — not housing finance or vehicle finance.",
        sub_sector="Gold loan",
        business_model="Gold-loan NBFC",
    ),
    "nbfc_housing": _fw(
        id="nbfc_housing",
        label="Housing finance",
        kpis=k.NBFC_HOUSING,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("gnpa", "aum", "nim"),
        acquire=_BANK_ACQ,
        material=("rbi", "nhb", "housing", "npa"),
        skip_cfo=True,
        lending=True,
        peer_note="Housing-finance companies only — not gold-loan NBFCs.",
        sub_sector="Housing finance",
        business_model="HFC",
    ),
    "it": _fw(
        id="it",
        label="IT services",
        kpis=k.IT,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("sales", "opm", "pat", "cfo_pat", "attrition", "tcv"),
        acquire=_IR_DEAL,
        material=("large deal", "attrition", "layoff", "constant currency", "guidance"),
        peer_note="IT services / BPO — not product-software or SaaS.",
        sub_sector="IT services",
        business_model="IT outsourcing",
    ),
    "software_product": _fw(
        id="software_product",
        label="Software / product tech",
        kpis=k.SOFTWARE_PRODUCT,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("sales", "opm", "cfo_pat"),
        acquire=_IR_DEAL,
        material=("arr", "churn", "guidance", "product launch"),
        peer_note="Product / SaaS — not IT services outsourcing.",
        sub_sector="Software product",
        business_model="Product / SaaS",
    ),
    "pharma": _fw(
        id="pharma",
        label="Pharma",
        kpis=k.PHARMA,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("sales", "opm", "rnd", "us_sales"),
        acquire=("financials", "ir", "filings", "news"),
        material=("usfda", "warning letter", "import alert", "form 483", "anda", "recall"),
        peer_note="Pharmaceutical manufacturers — not hospital chains or diagnostics.",
        sub_sector="Pharmaceuticals",
        business_model="Pharma manufacturer",
    ),
    "hospitals": _fw(
        id="hospitals",
        label="Hospitals",
        kpis=k.HOSPITALS,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("occupancy", "arpob", "sales", "opm", "beds"),
        acquire=_IR_REG,
        material=("occupancy", "bed", "acquisition", "capex"),
        peer_note="Hospital operators — not diagnostics labs or pharma.",
        sub_sector="Hospitals",
        business_model="Hospital chain",
    ),
    "diagnostics": _fw(
        id="diagnostics",
        label="Diagnostics",
        kpis=k.DIAGNOSTICS,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("test_volumes", "sales", "opm"),
        acquire=_IR_REG,
        material=("lab", "network", "acquisition"),
        peer_note="Diagnostics labs — not hospital operators.",
        sub_sector="Diagnostics",
        business_model="Diagnostics network",
    ),
    "auto": _fw(
        id="auto",
        label="Auto OEM",
        kpis=k.AUTO,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("volumes", "sales", "opm", "market_share"),
        acquire=_IR_REG,
        material=("volume", "launch", "recall", "ev", "bsvi"),
        peer_note="Vehicle OEMs of similar category (PV / CV / 2W / tractor) — not auto ancillaries.",
        sub_sector="Automobile OEM",
        business_model="OEM",
    ),
    "auto_ancillary": _fw(
        id="auto_ancillary",
        label="Auto ancillary",
        kpis=k.AUTO_ANCILLARY,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("sales", "opm", "oem_concentration"),
        acquire=_IR_REG,
        material=("oem", "ev", "order win", "capacity"),
        peer_note="Auto component makers — not vehicle OEMs.",
        sub_sector="Auto ancillary",
        business_model="Component supplier",
    ),
    "fmcg": _fw(
        id="fmcg",
        label="FMCG / staples",
        kpis=k.FMCG,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("volume_growth", "sales", "gm", "opm"),
        acquire=_IR_REG,
        material=("volume", "rural", "commodity", "gst"),
        peer_note="FMCG / consumer staples — not discretionary retail.",
        sub_sector="FMCG",
        business_model="Consumer staples",
    ),
    "consumer_discretionary": _fw(
        id="consumer_discretionary",
        label="Consumer discretionary",
        kpis=k.CONSUMER_DISC,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("sales", "opm", "sss"),
        acquire=_IR_REG,
        material=("same store", "store", "demand"),
        peer_note="Discretionary brands — not FMCG staples or grocery retail.",
        sub_sector="Consumer discretionary",
        business_model="Brand / lifestyle",
    ),
    "retail": _fw(
        id="retail",
        label="Retail",
        kpis=k.RETAIL,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("sss", "sales", "gm", "inventory_days"),
        acquire=_IR_REG,
        material=("same store", "store addition", "inventory"),
        peer_note="Retail operators — not FMCG manufacturers.",
        sub_sector="Retail",
        business_model="Retail chain",
    ),
    "capital_goods": _fw(
        id="capital_goods",
        label="Capital goods",
        kpis=k.CAPITAL_GOODS,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("order_book", "sales", "cfo_pat", "opm"),
        acquire=_IR_REG,
        material=("order", "order book", "award", "cancellation"),
        peer_note="Capital-goods / engineering — not commodity metals.",
        sub_sector="Capital goods",
        business_model="Engineering / capital goods",
    ),
    "industrials": _fw(
        id="industrials",
        label="Industrials",
        kpis=k.INDUSTRIALS,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("order_book", "sales", "cfo_pat", "opm"),
        acquire=_IR_REG,
        material=("order", "order book", "award"),
        peer_note="Industrial manufacturers — not commodity miners.",
        sub_sector="Industrials",
        business_model="Industrial manufacturer",
    ),
    "defence": _fw(
        id="defence",
        label="Defence",
        kpis=k.DEFENCE,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("order_book", "sales", "cfo_pat", "defence_orders"),
        acquire=_IR_REG,
        material=("order", "mod", "defence", "export order", "indigenisation"),
        peer_note="Defence OEMs / suppliers — not generic industrials.",
        sub_sector="Defence",
        business_model="Defence OEM / supplier",
    ),
    "infrastructure": _fw(
        id="infrastructure",
        label="Infrastructure / EPC",
        kpis=k.INFRASTRUCTURE,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("order_book", "sales", "receivable_days", "cfo_pat"),
        acquire=_IR_REG,
        material=("order", "arbitration", "nhai", "delay"),
        peer_note="EPC / infra contractors — not real-estate developers.",
        sub_sector="Infrastructure",
        business_model="EPC / infra",
    ),
    "cement": _fw(
        id="cement",
        label="Cement",
        kpis=k.CEMENT,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("volumes", "ebitda_tonne", "sales", "opm"),
        acquire=_IR_REG,
        material=("capacity", "realization", "fuel"),
        cycle_aware=True,
        peer_note="Cement producers — not generic industrials.",
        sub_sector="Cement",
        business_model="Cement producer",
    ),
    "metals": _fw(
        id="metals",
        label="Metals",
        kpis=k.METALS,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("volumes", "realization", "ebitda_tonne", "sales"),
        acquire=_IR_REG,
        material=("realization", "spread", "capacity", "coking coal"),
        cycle_aware=True,
        peer_note="Metal producers — not miners or capital-goods fabricators.",
        sub_sector="Metals",
        business_model="Metal producer",
    ),
    "mining": _fw(
        id="mining",
        label="Mining",
        kpis=k.MINING,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("production", "realization", "sales"),
        acquire=_IR_REG,
        material=("production", "royalty", "mine"),
        cycle_aware=True,
        peer_note="Miners — not downstream metal producers.",
        sub_sector="Mining",
        business_model="Miner",
    ),
    "chemicals": _fw(
        id="chemicals",
        label="Chemicals",
        kpis=k.CHEMICALS,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("sales", "opm", "gm"),
        acquire=_IR_REG,
        material=("capacity", "spread", "china"),
        peer_note="Bulk chemicals — not specialty chemicals.",
        sub_sector="Chemicals",
        business_model="Chemical producer",
    ),
    "specialty_chemicals": _fw(
        id="specialty_chemicals",
        label="Specialty chemicals",
        kpis=k.SPECIALTY_CHEMICALS,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("sales", "opm", "gm"),
        acquire=_IR_REG,
        material=("capacity", "product", "china plus one"),
        peer_note="Specialty chemicals — not bulk commodity chemicals.",
        sub_sector="Specialty chemicals",
        business_model="Specialty chemical",
    ),
    "oil_gas": _fw(
        id="oil_gas",
        label="Oil & gas",
        kpis=k.OIL_GAS,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("production", "realization", "sales"),
        acquire=_IR_REG,
        material=("production", "gas price", "subsidy"),
        cycle_aware=True,
        peer_note="Upstream oil & gas — not refiners.",
        sub_sector="Oil & gas",
        business_model="Upstream",
    ),
    "refining": _fw(
        id="refining",
        label="Refining",
        kpis=k.REFINING,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("grm", "throughput", "sales"),
        acquire=_IR_REG,
        material=("grm", "throughput", "crack"),
        cycle_aware=True,
        peer_note="Refiners — not upstream producers.",
        sub_sector="Refining",
        business_model="Refiner",
    ),
    "telecom": _fw(
        id="telecom",
        label="Telecom",
        kpis=k.TELECOM,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("subscribers", "arpu", "sales", "opm"),
        acquire=_IR_REG,
        material=("arpu", "tariff", "spectrum", "subscriber", "agr"),
        peer_note="Telecom operators — not media.",
        sub_sector="Telecom",
        business_model="Telecom operator",
    ),
    "utilities": _fw(
        id="utilities",
        label="Utilities",
        kpis=k.UTILITIES,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("sales", "opm", "capacity"),
        acquire=_IR_REG,
        material=("tariff", "cerc", "receivable"),
        peer_note="Regulated utilities — distinguish generator vs transmission.",
        sub_sector="Utilities",
        business_model="Utility",
    ),
    "power_generation": _fw(
        id="power_generation",
        label="Power generation",
        kpis=k.POWER_GEN,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("capacity", "plf", "sales"),
        acquire=_IR_REG,
        material=("plf", "ppa", "fuel", "capacity"),
        peer_note="Power generators — not transmission utilities.",
        sub_sector="Power generation",
        business_model="Generator",
    ),
    "power_transmission": _fw(
        id="power_transmission",
        label="Power transmission",
        kpis=k.POWER_TRANS,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("sales", "opm", "regulated_asset_base"),
        acquire=_IR_REG,
        material=("tariff", "cerc", "transmission"),
        peer_note="Transmission / distribution — not generators.",
        sub_sector="Power transmission",
        business_model="Transmission / distribution",
    ),
    "realty": _fw(
        id="realty",
        label="Real estate",
        kpis=k.REALTY,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("presales", "collections", "cfo_pat", "sales"),
        acquire=_IR_REG,
        material=("pre-sales", "launch", "debt", "rera"),
        peer_note="Developers — not REITs or infra EPC.",
        sub_sector="Real estate",
        business_model="Developer",
    ),
    "logistics": _fw(
        id="logistics",
        label="Logistics",
        kpis=k.LOGISTICS,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("volumes", "sales", "opm"),
        acquire=_IR_REG,
        material=("volume", "fleet", "freight"),
        peer_note="Logistics operators — not airlines.",
        sub_sector="Logistics",
        business_model="Logistics",
    ),
    "airlines": _fw(
        id="airlines",
        label="Airlines",
        kpis=k.AIRLINES,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("ask", "load_factor", "cask", "sales"),
        acquire=_IR_REG,
        material=("load factor", "ask", "fuel", "fleet"),
        peer_note="Airlines only.",
        sub_sector="Airlines",
        business_model="Airline",
    ),
    "hotels": _fw(
        id="hotels",
        label="Hotels",
        kpis=k.HOTELS,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("occupancy", "revpar", "arr", "sales"),
        acquire=_IR_REG,
        material=("occupancy", "revpar", "room"),
        peer_note="Hotel operators — not airlines or logistics.",
        sub_sector="Hotels",
        business_model="Hotel operator",
    ),
    "life_insurance": _fw(
        id="life_insurance",
        label="Life insurance",
        kpis=k.LIFE_INSURANCE,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("ape", "vnb_margin", "persistency", "solvency"),
        acquire=_IR_REG,
        material=("vnb", "solvency", "irdai", "persistency"),
        skip_cfo=True,
        peer_note="Life insurers — not general insurers or banks.",
        sub_sector="Life insurance",
        business_model="Life insurer",
    ),
    "general_insurance": _fw(
        id="general_insurance",
        label="General insurance",
        kpis=k.GENERAL_INSURANCE,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("gwp", "combined_ratio", "loss_ratio", "solvency"),
        acquire=_IR_REG,
        material=("combined ratio", "irdai", "cat", "solvency"),
        skip_cfo=True,
        peer_note="General / health insurers — not life insurers.",
        sub_sector="General insurance",
        business_model="General insurer",
    ),
    "exchange": _fw(
        id="exchange",
        label="Exchange / FMI",
        kpis=k.EXCHANGE,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("volumes", "sales", "opm"),
        acquire=_IR_REG,
        material=("sebi", "volume", "market share"),
        skip_cfo=True,
        peer_note="Exchanges / depositories / FMI — not brokers.",
        sub_sector="Exchange / FMI",
        business_model="Market infrastructure",
    ),
    "broker": _fw(
        id="broker",
        label="Broker",
        kpis=k.BROKER,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("active_clients", "sales", "opm"),
        acquire=_IR_REG,
        material=("sebi", "client", "margin"),
        skip_cfo=True,
        peer_note="Brokers — not exchanges.",
        sub_sector="Broking",
        business_model="Broker",
    ),
    "amc": _fw(
        id="amc",
        label="AMC",
        kpis=k.AMC,
        min_critical=2,
        min_decision=0.50,
        min_score=0.40,
        watch=("aum", "net_flows", "sales", "opm"),
        acquire=_IR_REG,
        material=("aum", "sip", "sebi", "flow"),
        skip_cfo=True,
        peer_note="Asset managers — not brokers or exchanges.",
        sub_sector="AMC",
        business_model="Asset manager",
    ),
    "media": _fw(
        id="media",
        label="Media",
        kpis=k.MEDIA,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("sales", "opm", "subscribers"),
        acquire=_IR_REG,
        material=("subscriber", "ad", "trp"),
        peer_note="Media / broadcasting — not telecom operators.",
        sub_sector="Media",
        business_model="Media",
    ),
    "textiles": _fw(
        id="textiles",
        label="Textiles",
        kpis=k.TEXTILES,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("sales", "opm", "gm"),
        acquire=_IR_REG,
        material=("cotton", "export", "capacity"),
        peer_note="Textile manufacturers.",
        sub_sector="Textiles",
        business_model="Textile manufacturer",
    ),
    "agri": _fw(
        id="agri",
        label="Agriculture / agri-inputs",
        kpis=k.AGRI,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("sales", "opm", "volumes"),
        acquire=_IR_REG,
        material=("monsoon", "subsidy", "channel"),
        peer_note="Agri-inputs / agribusiness — not FMCG foods unless branded staples dominate.",
        sub_sector="Agriculture",
        business_model="Agri-inputs",
    ),
    "generic": _fw(
        id="generic",
        label="Generic",
        kpis=k.GENERIC,
        min_critical=2,
        min_decision=0.45,
        min_score=0.40,
        watch=("sales", "opm", "pat", "cfo_pat", "roe"),
        acquire=("financials", "ir", "filings", "news"),
        material=(),
        peer_note="Fallback only — prefer a business-specific framework.",
        sub_sector="",
        business_model="",
    ),
}
