"""Stable decision vocabulary. Four concepts, not one overloaded state.

A. candidate_state  — lifecycle of the opportunity
B. decision         — investment judgment (BUY / WAIT / AVOID)
C. entry_state      — price/setup timing
D. execution_state  — whether paper/live can act
"""
from __future__ import annotations

from typing import Any, Mapping

# A. candidate states (reuse lifecycle names)
DISCOVERED = "DISCOVERED"
SCREENED = "SCREENED"
WATCH = "WATCH"
RESEARCHING = "RESEARCHING"
QUALIFIED = "QUALIFIED"
READY = "READY"
ENTERED = "ENTERED"
WAIT = "WAIT"
WAIT_EVIDENCE = "WAIT_EVIDENCE"
REJECTED = "REJECTED"
INVALIDATED = "INVALIDATED"
EXPIRED = "EXPIRED"
CLOSED = "CLOSED"

# B. decision
BUY = "BUY"
WAIT_DECISION = "WAIT"
AVOID = "AVOID"
NO_JUDGMENT = "NO_JUDGMENT"

# C. entry
ENTER_NOW = "ENTER_NOW"
WAIT_FOR_ENTRY = "WAIT_FOR_ENTRY"
EXTENDED = "EXTENDED"
NO_TRIGGER = "NO_TRIGGER"
NEAR_SETUP = "NEAR_SETUP"
BROKEN = "BROKEN"

# D. execution
NOT_APPLICABLE = "NOT_APPLICABLE"
ELIGIBLE = "ELIGIBLE"
BLOCKED_BROKER_AUTH = "BLOCKED_BROKER_AUTH"
BLOCKED_PORTFOLIO = "BLOCKED_PORTFOLIO"
BLOCKED_RISK = "BLOCKED_RISK"
BLOCKED_WINDOW = "BLOCKED_WINDOW"
PAPER_ENTERED = "PAPER_ENTERED"
SHADOW_NOT_EXECUTED = "SHADOW_NOT_EXECUTED"

# Stable reason codes — aliases of existing production codes where they exist.
from product.paper_autopilot import (  # noqa: E402
    BROKER_LOGIN_REQUIRED,
    CORRELATION_CAP,
    DD_GATE_FAILED,
    EMPIRICAL_GATE_FAILED,
    ENTRY_TOO_EXTENDED,
    EVIDENCE_POLICY_BLOCK,
    LIQUIDITY_FAILED,
    LOW_QUALITY_SETUP,
    MAX_PORTFOLIO_RISK,
    MAX_POSITIONS,
    NO_VALID_ENTRY,
    SECTOR_CAP,
    WAIT_FOR_ENTRY as WAIT_FOR_ENTRY_REASON,
)

NO_SETUP = "NO_SETUP"
LOW_LIQUIDITY = "LOW_LIQUIDITY"
EXTENDED_REASON = ENTRY_TOO_EXTENDED
ENTRY_NOT_TRIGGERED = WAIT_FOR_ENTRY_REASON
WEAK_SECTOR = "WEAK_SECTOR"
INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
BUSINESS_QUALITY_FAIL = "BUSINESS_QUALITY_FAIL"
FINANCIAL_QUALITY_FAIL = "FINANCIAL_QUALITY_FAIL"
PORTFOLIO_CONCENTRATION = MAX_POSITIONS
CORRELATION_LIMIT = CORRELATION_CAP
BROKER_AUTH_REQUIRED = BROKER_LOGIN_REQUIRED
STALE_CRITICAL_EVIDENCE = "STALE_CRITICAL_EVIDENCE"
DATA_INTEGRITY = "DATA_INTEGRITY"
UNACCEPTABLE_DOWNSIDE = "UNACCEPTABLE_DOWNSIDE"
REGIME_INCOMPATIBLE = "REGIME_INCOMPATIBLE"
INSUFFICIENT_INDEPENDENT_EVIDENCE = "INSUFFICIENT_INDEPENDENT_EVIDENCE"
WAIT_PORTFOLIO = "WAIT_PORTFOLIO"
WAIT_RATIONALLY_MAINTAINED = "WAIT_RATIONALLY_MAINTAINED"
MISSED_REENTRY = "MISSED_REENTRY"

# Non-judgments: lookup/analysis failures, not investment calls.
INVALID_SYMBOL = "INVALID_SYMBOL"
DATA_UNAVAILABLE = "DATA_UNAVAILABLE"
ANALYSIS_ERROR = "ANALYSIS_ERROR"
NON_JUDGMENT_CODES = frozenset({INVALID_SYMBOL, DATA_UNAVAILABLE, ANALYSIS_ERROR})
NON_JUDGMENT_DECISIONS = frozenset({NO_JUDGMENT})


def is_non_judgment(decision: str | None = None, reason_code: str | None = None) -> bool:
    if str(decision or "").upper() in NON_JUDGMENT_DECISIONS:
        return True
    return str(reason_code or "").upper() in NON_JUDGMENT_CODES


def is_judgment_row(row: Mapping[str, Any] | None) -> bool:
    payload = row or {}
    return not is_non_judgment(payload.get("decision"), payload.get("reason_code"))

HARD_VETO_CODES = frozenset({
    LOW_LIQUIDITY, LIQUIDITY_FAILED, ENTRY_TOO_EXTENDED, STALE_CRITICAL_EVIDENCE,
    BUSINESS_QUALITY_FAIL, FINANCIAL_QUALITY_FAIL, DD_GATE_FAILED,
    NO_VALID_ENTRY, UNACCEPTABLE_DOWNSIDE, PORTFOLIO_CONCENTRATION,
    CORRELATION_LIMIT, MAX_PORTFOLIO_RISK, SECTOR_CAP, DATA_INTEGRITY,
    REGIME_INCOMPATIBLE, EMPIRICAL_GATE_FAILED, EVIDENCE_POLICY_BLOCK,
})

ENTRY_FROM_CARD = {
    "ready": ENTER_NOW,
    "extended": EXTENDED,
    "near_setup": NEAR_SETUP,
    "watch": WAIT_FOR_ENTRY,
    "broken": BROKEN,
}


def entry_from_card(card: dict) -> str:
    raw = str(card.get("entry_state") or "").lower()
    if card.get("chase_risk"):
        return EXTENDED
    return ENTRY_FROM_CARD.get(raw, NO_TRIGGER)
