"""First-pass inventory of historical sources already in the repository.

Do not create a second archive when one of these already exists.
Screener cache is current-world and is never a PIT source.
"""
from __future__ import annotations

from typing import Any


def source_inventory() -> list[dict[str, Any]]:
    return [
        {
            "id": "nse_announcements",
            "path": "logs/research_evidence/{SYM}/autonomy/nse_0.json",
            "contains": "Exchange corporate announcements (headline, attachment URL, sort_date)",
            "historical_depth": "Whatever last acquire kept (INFY has 2026 rows; most walk-forward names absent)",
            "publication_date": "sort_date / an_dt / exchdisstime — PIT-usable when present",
            "authority": "exchange",
            "pit_safe": True,
            "can_backfill": True,
            "parser": "product.pit_ingest.ingest_announcement_row",
            "storage": "raw JSON + pit_warehouse",
            "gaps": "Facts previously dropped dates. Only ~29 autonomy folders exist.",
        },
        {
            "id": "nse_financial_results",
            "path": "logs/research_evidence/{SYM}/autonomy/nse_1.json",
            "contains": "Result filing metadata (period, filingDate, XBRL/HTML link). Rarely includes P&L numbers.",
            "historical_depth": "INFY/GUFICBIO often 2005–2012 old-format only; CLEAN is []",
            "publication_date": "filingDate / broadCastDate — '-' is unverified",
            "authority": "exchange",
            "pit_safe": True,
            "can_backfill": True,
            "parser": "product.pit_ingest.ingest_result_row",
            "storage": "raw JSON + pit_warehouse",
            "gaps": "No XBRL number parser. Metadata ≠ FINANCIAL_QUALITY.",
        },
        {
            "id": "nse_annual_reports",
            "path": "logs/research_evidence/{SYM}/autonomy/nse_annual_reports.json + nse_ar_*.pdf",
            "contains": "Annual-report file names / PDFs",
            "historical_depth": "Last two PDFs when acquire succeeded",
            "publication_date": "None. Filename is not a date.",
            "authority": "exchange / company",
            "pit_safe": False,
            "can_backfill": "index yes; eligibility no until a publication stamp exists",
            "parser": "product.pit_ingest.ingest_annual_report_index",
            "storage": "raw PDF + unverified warehouse row",
            "gaps": "PUBLICATION_DATE_UNKNOWN — excluded from replay.",
        },
        {
            "id": "screener_cache",
            "path": "data/fundamentals_cache.db + autonomy/screener.json",
            "contains": "Current Screener snapshot and precomputed ratios",
            "historical_depth": "Latest fetch only",
            "publication_date": "Period labels, not publication dates",
            "authority": "trusted secondary",
            "pit_safe": False,
            "can_backfill": False,
            "parser": "fundamentals/screener_deep.py",
            "storage": "SQLite cache",
            "gaps": "Must never enter historical T. Not ingested by the warehouse.",
        },
        {
            "id": "autonomy_facts",
            "path": "logs/research_evidence/{SYM}/autonomy/autonomy_facts.json",
            "contains": "Extracted KPIs from the latest acquire",
            "historical_depth": "Last acquire",
            "publication_date": "acquired_at + period labels only",
            "authority": "derived",
            "pit_safe": False,
            "can_backfill": False,
            "parser": "product.due_diligence.acquire",
            "storage": "JSON",
            "gaps": "Live research only. Historical as_of skips this file.",
        },
        {
            "id": "bhavcopy",
            "path": "logs/bhav/",
            "contains": "Official NSE OHLCV",
            "historical_depth": "~765 sessions",
            "publication_date": "session date",
            "authority": "exchange",
            "pit_safe": True,
            "can_backfill": True,
            "parser": "data.bhavcopy_store",
            "storage": "daily files",
            "gaps": "Market-data family only.",
        },
        {
            "id": "index_ohlc",
            "path": "logs/indices/",
            "contains": "Index OHLC",
            "historical_depth": "On-disk index history",
            "publication_date": "session date",
            "authority": "exchange",
            "pit_safe": True,
            "can_backfill": True,
            "parser": "existing index loaders",
            "storage": "files",
            "gaps": "No dated index-membership history.",
        },
        {
            "id": "universe_pit",
            "path": "data/nse_universe.py point_in_time_universe",
            "contains": "Intended dated membership",
            "historical_depth": "logs/universe_history.json missing",
            "publication_date": "n/a",
            "authority": "internal",
            "pit_safe": False,
            "can_backfill": True,
            "parser": "data.nse_universe",
            "storage": "missing history file",
            "gaps": "Replay falls back to 'had a bar that day'.",
        },
        {
            "id": "corporate_actions",
            "path": "data/corporate_actions*.py",
            "contains": "Would-be CA events",
            "historical_depth": "logs/ca_events.json missing",
            "publication_date": "would be event date",
            "authority": "exchange",
            "pit_safe": True,
            "can_backfill": True,
            "parser": "data.corporate_actions",
            "storage": "missing",
            "gaps": "Not yet a warehouse source.",
        },
        {
            "id": "news_curator",
            "path": "logs/news_curator.sqlite3",
            "contains": "Recent curated headlines with published_at",
            "historical_depth": "rolling, not a multi-year archive",
            "publication_date": "published_at",
            "authority": "mixed / media",
            "pit_safe": "partial when timestamped; media is not synthesized for replay",
            "can_backfill": False,
            "parser": "news.curator_store",
            "storage": "SQLite",
            "gaps": "Not wired into historical investigate. Unsupported media → catalyst unavailable.",
        },
        {
            "id": "user_uploads",
            "path": "reporting/evidence_intake.py",
            "contains": "Operator-supplied structured rows",
            "historical_depth": "sparse",
            "publication_date": "as_of_date when supplied",
            "authority": "operator / attached source",
            "pit_safe": True,
            "can_backfill": False,
            "parser": "reporting.evidence_intake",
            "storage": "intake store",
            "gaps": "Live path only. Historical as_of uses an empty row loader.",
        },
        {
            "id": "moneycontrol",
            "path": "fallback scrape in acquire",
            "contains": "Latest page only",
            "historical_depth": "none",
            "publication_date": "none",
            "authority": "fallback",
            "pit_safe": False,
            "can_backfill": False,
            "parser": "brittle DOM",
            "storage": "none",
            "gaps": "Not a foundation. Not used by the warehouse.",
        },
        {
            "id": "xbrl",
            "path": "URLs inside nse_1.json",
            "contains": "Structured result instances",
            "historical_depth": "linked, not downloaded",
            "publication_date": "would inherit filingDate",
            "authority": "official structured",
            "pit_safe": True,
            "can_backfill": True,
            "parser": "not implemented",
            "storage": "none",
            "gaps": "Highest-value missing parser for FINANCIALS STRONG.",
        },
        {
            "id": "sector_map",
            "path": "data/nse_universe.py # Sector comments + scan/sector_heat.sector_of",
            "contains": "Current static classification",
            "historical_depth": "none — not versioned",
            "publication_date": "n/a",
            "authority": "internal convenience",
            "pit_safe": False,
            "can_backfill": False,
            "parser": "scan.sector_heat.sector_of",
            "storage": "source comments",
            "gaps": "Never a SECTOR_CONTEXT family confirm in replay.",
        },
    ]
