[theme]
base                     = "dark"
primaryColor             = "#36d9ff"
backgroundColor          = "#060a12"
secondaryBackgroundColor = "#0d1523"
textColor                = "#eef5ff"
font                     = "sans serif"

[server]
headless                 = true
